server:
  port: 26719
  hostname: http://localhost/ #前缀域名

service:
  threads: 200
  counter: redis # inner 使用内部还是Redis进行计数

redis:
  redishost: 127.0.0.1
  redisport: 6379
  status: false # 是否初始化Redis计数器

